export const RECEIVE_ADDRESS = 'receive_address' // 接收地址信息
export const RECEIVE_CATEGORYS = 'receive_categorys' // 接收分类数组
export const RECEIVE_SHOPS = 'receive_shops' // 接收商家数组
export const RECEIVE_USER = 'receive_user' //保存用户
export const RECEIVE_TOKEN = 'receive_token'//保存token
export const DELETE_USER = 'delete_user' //退出登录
export const RECEIVE_INFO = 'receive_info'//保存
export const RECEIVE_GOODS = 'receive_goods'//保存
export const RECEIVE_RATINGS = 'receive_ratings'//保存
